### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Aleksey-Terzi** [DevotedMC/Humbug#14]
1) Move all event handlers to appropriate package and classes (like we have in another plugins)

2) Add Override attribute to all overridden methods

3) Expose all deprecated methods to DeprecatedMethods class

4) Expose all reflection-related code to special package. For example to package "reflection" with one (for ex. ReflectionHelper) or more classes

This should simplify future upgrades and bug fixing.

**Comment by Aleksey-Terzi** [comment]
@ProgrammerDan 
I would be happy to implement this task (later), but I need to know your opinion if this reasonable for you or no.

**Comment by ProgrammerDan** [comment]
Oh, crap, I missed this.

No, don't do this, it's a waste of time.

Humbug is deprecated, I keep it updated only because I'm too lazy to finish what I started.

SimpleAdminHacks is intended to hold all Humbug-like functionality. Do not invest time in making Humbug better, just move hacks and fixes over to SimpleAdminHacks.
